export type DomainAtom =
  | 'pm-domain/ai-tech'
  | 'pm-domain/politics'
  | 'pm-domain/crypto'
  | 'pm-domain/sports'
  | 'pm-domain/economics'
  | 'pm-domain/science'
  | 'pm-domain/culture'
  | 'pm-domain/weather'
  | 'pm-domain/geopolitics'
